// card-files.mjs — the per-card data behind /card?id=… and the nav card search (Sep 30 2026, Mo: "search individual cards
// … pulls up the card page (in an index already) that gives them all the options": raw, PSA 9, PSA 10, TAG).
//
// data/cards/<tk>.json   — written by build-sector-index.mjs on every bake (identity, raw sold mark, weight, eBay phrase, photo key)
// data/cards/g-<tk>.json — written by build-card-ladder.mjs (graded sold marks); the card page merges the two
// data/card-search.json  — rebuilt from every data/cards/<tk>.json: [id, label, set short name, raw mark]
import fs from "node:fs";
import path from "node:path";

export const cardSlug = (num) => String(num).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
export const cardId = (tk, num) => `${tk.toLowerCase()}-${cardSlug(num)}`;
// raw = an ungraded copy; graded words out so the Raw button opens raw listings only
export const RAW_NOT = "-psa -cgc -bgs -sgc -tag -beckett -graded -slab";
export const WOTC = new Set(["BS99", "JU99", "FO99", "TR00", "NG00", "ND02"]);
// edition indices (Sep 30 2026, Mo: "make a respective index for those two" — 1st Edition and Shadowless are their own sets)
export const EDITION = { BS1E: "1st", JU1E: "1st", FO1E: "1st", TR1E: "1st", NG1E: "1st", ND1E: "1st", BSSL: "shadowless" };

export function writeCardFile(ROOT, x, c, rows, imgAttr, dry) {
  const dir = path.join(ROOT, "data/cards");
  const h = x.history || [], last = h[h.length - 1];
  const bv = rows.reduce((s, b) => s + b.price * b.w, 0);
  const doc = {
    _comment: "GENERATED by tools/build-sector-index.mjs (bake) — one row per basket card for /card?id=. raw = the index's own dated sold mark (30-day median of clean ungraded sales). Graded marks live in g-<tk>.json.",
    ticker: x.ticker, name: c.name, set: c.set, page: c.page, theme: c.theme, asOf: last ? last.date : x.inception, wotc: WOTC.has(x.ticker) || !!EDITION[x.ticker], ed: EDITION[x.ticker] || (WOTC.has(x.ticker) ? "unl" : null), window: (x.screen && x.screen.window) || 30,
    level: last ? last.level : null,
    cards: rows.map((b, i) => ({ id: cardId(x.ticker, b.num), num: String(b.num), name: b.name, path: b.path, rank: i + 1, raw: b.price, n30: b.n30, rawAsOf: b.asOf || (last && last.date), w: bv ? Math.round((b.price * b.w / bv) * 10000) / 100 : null, q: c.ebayQuery(b.name, b.num), img: imgAttr(b, c) })),
  };
  if (dry) return;
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, `${x.ticker.toLowerCase()}.json`), JSON.stringify(doc) + "\n");
  writeSearch(ROOT);
}

export function writeSearch(ROOT) {
  const dir = path.join(ROOT, "data/cards");
  const out = [];
  for (const f of fs.readdirSync(dir).filter((f) => /^[a-z0-9]+\.json$/.test(f)).sort()) {
    const d = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    const short = String(d.set).replace(/^Pokémon TCG /, "").replace(/ \(Unlimited\)$/, "");
    for (const cd of d.cards) out.push([cd.id, `${cd.name} #${cd.num}`, short, cd.raw]);
  }
  fs.writeFileSync(path.join(ROOT, "data/card-search.json"), JSON.stringify({ _comment: "GENERATED from data/cards/*.json — nav card search: [id, card, set, raw sold mark]", cards: out }) + "\n");
}
