#!/usr/bin/env node
// build-rarity.mjs — data/kb/pokemon-rarity.json: printed rarity for every card in the sets the Pokémon indices track.
//
// Why (Mo, Oct 6 2026: "holos are more important than non-holos and must be in the Pokémon set-index baskets"): the sector
// model's liquidity screen was dropping exactly the cards that carry a set — Skyridge held 3 of its 38 holo-tier slots, the
// Crystals and Gengar H9 among the 35 out. The HOLO RULE in tools/build-sector-index.mjs makes every holo-tier slot a
// standing constituent, and it needs to know which slots those are. Source: the pokemon-tcg-data mirror of the pokemontcg.io
// API (the same project whose scans the index pages already use), one JSON per set, read once and committed so every
// build is offline and reproducible. Re-run when a new set joins the indices (add its id to SETS) or to refresh.
//
// Usage: node tools/kb/build-rarity.mjs [--set <id>,<id>]     (default: every id in SETS)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const OUT = path.join(ROOT, "data/kb/pokemon-rarity.json");
const SRC = "https://raw.githubusercontent.com/PokemonTCG/pokemon-tcg-data/master/cards/en/";
// pokemontcg.io set ids ↔ the index tickers that read them (the same ids the pages' imgSrc scans use)
export const SETS = {
  base1: "Base Set (BS99 BS1E BSSL)", base2: "Jungle (JU99 JU1E)", base3: "Fossil (FO99 FO1E)", base5: "Team Rocket (TR00 TR1E)",
  neo1: "Neo Genesis (NG00 NG1E)", neo2: "Neo Discovery (NDC01 NDC1E)", neo3: "Neo Revelation (NR01 NR1E)", neo4: "Neo Destiny (ND02 ND1E)",
  ecard2: "Aquapolis (AQ03)", ecard3: "Skyridge (SK03)", sm115: "Hidden Fates main (HF19)", sma: "Hidden Fates Shiny Vault (HF19)",
  sm9: "Team Up (TU19)", swsh7: "Evolving Skies (EVS21)", cel25: "Celebrations main (CEL21)", cel25c: "Celebrations Classic Collection (CEL21)",
  swsh12pt5: "Crown Zenith main (CZ23)", swsh12pt5gg: "Crown Zenith Galarian Gallery (CZ23)", sv3pt5: "151 (SV151)", sv8: "Surging Sparks (SSP24)",
  me1: "Mega Evolution (MEG25)", sv8pt5: "Prismatic Evolutions (PRIS25)", sv10: "Destined Rivals (DR25)",
};
const args = process.argv.slice(2);
const only = args.includes("--set") ? args[args.indexOf("--set") + 1].split(",") : Object.keys(SETS);
let doc = { sets: {} };
try { doc = JSON.parse(fs.readFileSync(OUT, "utf8")); } catch (e) {}
doc._comment = "GENERATED by tools/kb/build-rarity.mjs from the pokemon-tcg-data mirror (pokemontcg.io). sets.<id> = [number, name, rarity] per card; the Classic Collection (cel25c) is written as its own rarity. Read by tools/lib/holo-tier.mjs for the HOLO RULE (Mo, Oct 6 2026): holo-tier slots are standing index constituents.";
doc.source = SRC;
doc.fetched = new Date().toISOString().slice(0, 10);
doc.sets = doc.sets || {};
for (const id of only) {
  const r = await fetch(SRC + id + ".json", { headers: { "User-Agent": "shopcardhub-kb" } });
  if (!r.ok) { console.error(`${id}: HTTP ${r.status} — kept the previous copy`); continue; }
  const cards = await r.json();
  doc.sets[id] = cards.map((c) => [String(c.number), c.name, id === "cel25c" ? "Classic Collection" : (c.rarity || null)]);
  console.log(`${id.padEnd(12)} ${String(cards.length).padStart(3)} cards — ${SETS[id] || ""}`);
}
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify(doc) + "\n");
console.log(`wrote ${path.relative(ROOT, OUT)} (${Object.keys(doc.sets).length} sets)`);
