#!/usr/bin/env node
// build-signup.mjs — the email capture on every commercial page (Sep 26 2026, Mo: "go, I approve all").
//
// The finding behind it: the list had 4 subscribers. The five biggest landing pages
// (/pokemon-30th-anniversary-2026, /bowman-football, /best-hobby-boxes-2026,
// /bowman-chrome-baseball-2026, /nfl-rookie-cards-2026) carried NO signup form; the pages that had
// one put it below the fold with a pitch that promised nothing specific. Retention on a data site is
// the list, so: one component (js/signup.js), one concrete promise, directly under the buy strip on
// every page that has one (+ the 30th page's buy box), source = page slug for the KPI.
//
// Pages that already carry the Tuesday Tape capture (#tapecap — the six Pokémon chase indices and
// /bowman-bangers) keep their block; only the pitch text is rewritten to the same promise.
//
// Contract: machine-owned between SIGNUP markers. Usage: node tools/build-signup.mjs [--check]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const START = "<!-- SIGNUP:START";
const END = "<!-- SIGNUP:END -->";

// styles live in js/signup.js (injected once per page) so hand-placed instances (home) get them too

const block = (slug, where = "under the buy strip") => `${START} — email capture ${where}. Generated by tools/build-signup.mjs; rendered by /js/signup.js. Do not hand-edit. -->
<div class="sch-signup" data-signup="${slug}" data-variant="tape"></div>
<script src="/js/signup.js?v=2" defer></script>
${END}`;

// the new promise, for pages that keep their own #tapecap block
const OLD_PITCH = /This board(?:&#x27;|&#39;|')s weekly moves in your inbox\. Sold comps only, one email, Tuesdays\./g;
const NEW_PITCH = "The Monday close of every set index, the week&rsquo;s movers, and the chase cards&rsquo; sold marks. One email, Tuesdays. Free.";

const strip = JSON.parse(fs.readFileSync(path.join(REPO, "data/buy-strip.json"), "utf8"));
const targets = new Set(Object.keys(strip.pages || {}));
targets.add("pokemon-30th-anniversary-2026");

// Index pages (Oct 7 2026 weekly, build-order #2 — signup-missing-on-index-pages-2026-10-05): every *-index page and
// /indices gets the same capture under the index board, independent of buy-strip.json. Pages that already carry their
// own capture (#tapecap on the six chase indices; the Bowman pages' strip capture) are left alone — one capture per page (R26).
const isIndexPage = (slug) => slug === "indices" || /-index$/.test(slug);
function indexAnchor(html, slug) {
  if (slug === "indices") { const k = '<div id="sections"></div>'; const i = html.indexOf(k); return i === -1 ? -1 : i + k.length; }
  const bb = html.indexOf("<!-- BUYBOX:END -->"); if (bb === -1) return -1;
  const m = /<!-- ([A-Z0-9]+):START -->/.exec(html.slice(bb)); if (!m) return -1;
  const endTag = `<!-- ${m[1]}:END -->`; const e = html.indexOf(endTag, bb); return e === -1 ? -1 : e + endTag.length;
}

const changed = [], skipped = [];
for (const f of fs.readdirSync(REPO).filter((n) => n.endsWith(".html"))) {
  const slug = f.replace(/\.html$/, "");
  const p = path.join(REPO, f);
  let html = fs.readFileSync(p, "utf8"), next = html;
  // 1. pitch rewrite wherever the old sentence lives (index pages, bangers, home)
  next = next.replace(OLD_PITCH, NEW_PITCH);
  // 2. the component, on strip pages + the 30th page that have no capture of their own
  if (targets.has(slug)) {
    if (next.includes(START)) {
      const a = next.indexOf(START), b = next.indexOf(END, a);
      if (b === -1) throw new Error(`${f}: SIGNUP:START without END`);
      next = next.slice(0, a) + block(slug) + next.slice(b + END.length);
    } else if (!/api\/subscribe/.test(next)) {
      const anchor = next.includes("<!-- BUYSTRIP:END -->") ? "<!-- BUYSTRIP:END -->" : next.includes("<!-- BUYBOX:END -->") ? "<!-- BUYBOX:END -->" : null;
      if (!anchor) { skipped.push(`${slug} — no strip/buybox anchor`); }
      else { const at = next.indexOf(anchor) + anchor.length; next = next.slice(0, at) + "\n" + block(slug) + next.slice(at); }
    }
  }
  // 3. index pages: capture under the board when the page has none of its own
  if (!targets.has(slug) && isIndexPage(slug)) {
    if (next.includes(START)) {
      const a = next.indexOf(START), b = next.indexOf(END, a);
      if (b === -1) throw new Error(`${f}: SIGNUP:START without END`);
      next = next.slice(0, a) + block(slug, "under the index board") + next.slice(b + END.length);
    } else if (!/api\/subscribe/.test(next)) {
      const at = indexAnchor(next, slug);
      if (at === -1) skipped.push(`${slug} — no index-board anchor`);
      else next = next.slice(0, at) + "\n" + block(slug, "under the index board") + next.slice(at);
    }
  }
  if (next !== html) { changed.push(slug); if (!CHECK) fs.writeFileSync(p, next); }
}
console.log(`${CHECK ? "check" : "write"}: ${changed.length} page(s) ${CHECK ? "stale" : "updated"}`);
for (const s of skipped) console.log("  skip " + s);
if (CHECK && changed.length) process.exit(1);
